services:
  api:
    build: 
      context: ./applications/api
      dockerfile: Dockerfile
    ports:
      - "4345:4345"
    environment:
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@postgres:5432/deep_project_db"
    depends_on:
      - postgres
    
  webapp:
    build: 
      context: ./applications/panel-webapp
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: "http://localhost:4345"
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped
  
  postgres:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_DB: deep_project_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./applications/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
