FROM python:3.13.5-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 4345

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "4345"]
