// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:4345' | (string & {});
};

/**
 * Body_upload_product_vectors_deep_post
 */
export type BodyUploadProductVectorsDeepPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_product_vectors_products_vectors_post
 */
export type BodyUploadProductVectorsProductsVectorsPost = {
    /**
     * Product Code
     */
    product_code: string;
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LowStockProduct
 */
export type LowStockProduct = {
    /**
     * Product Code
     */
    product_code: string;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * ProductSchema
 */
export type ProductSchema = {
    /**
     * Product Code
     */
    product_code: string;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Price
     */
    price: number;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Shelf
     */
    shelf?: string | null;
    /**
     * Image Id
     */
    image_id?: Array<string>;
};

/**
 * ProductStatisticsResponse
 */
export type ProductStatisticsResponse = {
    /**
     * Total Products
     */
    total_products: number;
    /**
     * Total Quantity
     */
    total_quantity: number;
    /**
     * Total Categories
     */
    total_categories: number;
    /**
     * Low Stock Products
     */
    low_stock_products: Array<LowStockProduct>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetProductsProductsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products';
};

export type GetProductsProductsGetResponses = {
    /**
     * Response Get Products Products Get
     *
     * Successful Response
     */
    200: Array<ProductSchema>;
};

export type GetProductsProductsGetResponse = GetProductsProductsGetResponses[keyof GetProductsProductsGetResponses];

export type AddProductProductsPostData = {
    body: ProductSchema;
    path?: never;
    query?: never;
    url: '/products';
};

export type AddProductProductsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddProductProductsPostError = AddProductProductsPostErrors[keyof AddProductProductsPostErrors];

export type AddProductProductsPostResponses = {
    /**
     * Successful Response
     */
    200: ProductSchema;
};

export type AddProductProductsPostResponse = AddProductProductsPostResponses[keyof AddProductProductsPostResponses];

export type GetProductStatisticsProductsStatisticsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products/statistics';
};

export type GetProductStatisticsProductsStatisticsGetResponses = {
    /**
     * Successful Response
     */
    200: ProductStatisticsResponse;
};

export type GetProductStatisticsProductsStatisticsGetResponse = GetProductStatisticsProductsStatisticsGetResponses[keyof GetProductStatisticsProductsStatisticsGetResponses];

export type DeleteProductProductsProductCodeDeleteData = {
    body?: never;
    path: {
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/products/{product_code}';
};

export type DeleteProductProductsProductCodeDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProductProductsProductCodeDeleteError = DeleteProductProductsProductCodeDeleteErrors[keyof DeleteProductProductsProductCodeDeleteErrors];

export type DeleteProductProductsProductCodeDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProductProductsProductCodeDeleteResponse = DeleteProductProductsProductCodeDeleteResponses[keyof DeleteProductProductsProductCodeDeleteResponses];

export type GetProductDetailsProductsProductCodeGetData = {
    body?: never;
    path: {
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/products/{product_code}';
};

export type GetProductDetailsProductsProductCodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProductDetailsProductsProductCodeGetError = GetProductDetailsProductsProductCodeGetErrors[keyof GetProductDetailsProductsProductCodeGetErrors];

export type GetProductDetailsProductsProductCodeGetResponses = {
    /**
     * Successful Response
     */
    200: ProductSchema;
};

export type GetProductDetailsProductsProductCodeGetResponse = GetProductDetailsProductsProductCodeGetResponses[keyof GetProductDetailsProductsProductCodeGetResponses];

export type UpdateProductProductsProductCodePutData = {
    body: ProductSchema;
    path: {
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/products/{product_code}';
};

export type UpdateProductProductsProductCodePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProductProductsProductCodePutError = UpdateProductProductsProductCodePutErrors[keyof UpdateProductProductsProductCodePutErrors];

export type UpdateProductProductsProductCodePutResponses = {
    /**
     * Successful Response
     */
    200: ProductSchema;
};

export type UpdateProductProductsProductCodePutResponse = UpdateProductProductsProductCodePutResponses[keyof UpdateProductProductsProductCodePutResponses];

export type UploadProductVectorsProductsVectorsPostData = {
    body: BodyUploadProductVectorsProductsVectorsPost;
    path?: never;
    query?: never;
    url: '/products-vectors';
};

export type UploadProductVectorsProductsVectorsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadProductVectorsProductsVectorsPostError = UploadProductVectorsProductsVectorsPostErrors[keyof UploadProductVectorsProductsVectorsPostErrors];

export type UploadProductVectorsProductsVectorsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadProductVectorsDeepPostData = {
    body: BodyUploadProductVectorsDeepPost;
    path?: never;
    query?: never;
    url: '/deep';
};

export type UploadProductVectorsDeepPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadProductVectorsDeepPostError = UploadProductVectorsDeepPostErrors[keyof UploadProductVectorsDeepPostErrors];

export type UploadProductVectorsDeepPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteProductProductsImageIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/products/image/{id}';
};

export type DeleteProductProductsImageIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProductProductsImageIdDeleteError = DeleteProductProductsImageIdDeleteErrors[keyof DeleteProductProductsImageIdDeleteErrors];

export type DeleteProductProductsImageIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProductProductsImageIdDeleteResponse = DeleteProductProductsImageIdDeleteResponses[keyof DeleteProductProductsImageIdDeleteResponses];

export type GetProductImageProductsImageIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/products/image/{id}';
};

export type GetProductImageProductsImageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProductImageProductsImageIdGetError = GetProductImageProductsImageIdGetErrors[keyof GetProductImageProductsImageIdGetErrors];

export type GetProductImageProductsImageIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
