// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Body_upload_product_vectors_deep_post
 */
export const zBodyUploadProductVectorsDeepPost = z.object({
    file: z.string()
});

/**
 * Body_upload_product_vectors_products_vectors_post
 */
export const zBodyUploadProductVectorsProductsVectorsPost = z.object({
    product_code: z.string(),
    files: z.array(z.string())
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([
        z.string(),
        z.int()
    ])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

/**
 * LowStockProduct
 */
export const zLowStockProduct = z.object({
    product_code: z.string(),
    product_name: z.string(),
    quantity: z.int()
});

/**
 * ProductSchema
 */
export const zProductSchema = z.object({
    product_code: z.string(),
    product_name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    price: z.number(),
    quantity: z.int(),
    category: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    unit: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    shelf: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    image_id: z.optional(z.array(z.uuid()))
});

/**
 * ProductStatisticsResponse
 */
export const zProductStatisticsResponse = z.object({
    total_products: z.int(),
    total_quantity: z.int(),
    total_categories: z.int(),
    low_stock_products: z.array(zLowStockProduct)
});

export const zGetProductsProductsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get Products Products Get
 *
 * Successful Response
 */
export const zGetProductsProductsGetResponse = z.array(zProductSchema);

export const zAddProductProductsPostData = z.object({
    body: zProductSchema,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAddProductProductsPostResponse = zProductSchema;

export const zGetProductStatisticsProductsStatisticsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetProductStatisticsProductsStatisticsGetResponse = zProductStatisticsResponse;

export const zDeleteProductProductsProductCodeDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_code: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDeleteProductProductsProductCodeDeleteResponse = z.void();

export const zGetProductDetailsProductsProductCodeGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        product_code: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetProductDetailsProductsProductCodeGetResponse = zProductSchema;

export const zUpdateProductProductsProductCodePutData = z.object({
    body: zProductSchema,
    path: z.object({
        product_code: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zUpdateProductProductsProductCodePutResponse = zProductSchema;

export const zUploadProductVectorsProductsVectorsPostData = z.object({
    body: zBodyUploadProductVectorsProductsVectorsPost,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zUploadProductVectorsDeepPostData = z.object({
    body: zBodyUploadProductVectorsDeepPost,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zDeleteProductProductsImageIdDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDeleteProductProductsImageIdDeleteResponse = z.void();

export const zGetProductImageProductsImageIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});
